### ISSUE TITLE
Documentation on how to run codeception tests under VM

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#260]
I'm having trouble running `codeception` tests under the virtual machine. Running them from the host machine is fine but requires certain setup on the host. If someone has managed to run both unit and acceptance tests using local browser and remote interpreter (PHP / webserver / MySQL) on the VM, I'd be thankful to see a very short explanation, that I'll help to turn into step-by-step guide myself.

**Comment by trntv** [comment]
Is it about docker or vagrant?

**Comment by davidjeddy** [comment]
@ddinchev as @trntv stated vagrant is how we have our installs setup. Would highly recommend it.

**Comment by ddinchev** [comment]
@davidjeddy sorry for the super late reply - I'm using vagrant. I still don't see a way to run codeception tests under the VM. We need to change the configuration so that it uses PhantomJS for acceptance tests.

**Comment by davidjeddy** [comment]
@ddinchev This might help, here is our codeception config setup:

./tests/codeception.yml
```
actor: Tester
paths:
    tests: codeception
    log: codeception/_output
    data: codeception/_data
    helpers: codeception/_support
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 2048M
    log: true
    colors: true
config:
    # the entry script URL (with host info) for functional and acceptance tests
    # PLEASE ADJUST IT TO THE ACTUAL ENTRY SCRIPT URL
    test_entry_url: http://localhost:8080/index-test.php
```

then the ./tests/codeception/acceptance.suite.yml
```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - Db
AcceptanceTests#Selenium
    config:
        PhpBrowser:
            url: http://localhost:8080/index-test.php
        Db:
            dsn: 'mysql:host=localhost;dbname=tradesf_test'
            user: 'root'
            password: ''
            dump: 'codeception/_data/dump.sql'
            populate: true
            cleanup: true
            reconnect: true
```

and finally our ./test/codeception/config/config.php and acceptance.php
```
<?php
/**
 * Application configuration for acceptance tests
 */
$testConfig = [
    'components' => [
        'request' => [
            'cookieValidationKey'  => 'test',
            'enableCsrfValidation' => false,
        ],
    ],
    'params' => [
        'testAdminUser' => [
            'username' => 'admin',
            'password' => 'admin',
            'firstname'=> 'Admin',
            'lastname' => 'Istrator'
        ],
        'counter' => 5,
    ]
];

defined('YII_APP_BASE_PATH') or define('YII_APP_BASE_PATH', dirname(dirname(dirname(dirname(__DIR__)))));
$config = yii\helpers\ArrayHelper::merge(
    // Common Config
    require(YII_APP_BASE_PATH . '/humhub/config/common.php'),
    // Web Config
    require(YII_APP_BASE_PATH . '/humhub/config/web.php'),

    // Common Config
    require(YII_APP_BASE_PATH . '/tradesfactor/config/common.php'),
    // Web Config
    require(YII_APP_BASE_PATH . '/tradesfactor/config/web.php'),

    // Test Common Config
    require(__DIR__ . '/config.php'),
    // Acceptance Test Config
    $testConfig
);

return $config;

```
```
<?php

/**
 * Application configuration shared by all test types
 */
return [
    'name'     => 'TradesFactor Test',
    'language' => 'en-US',
    'params' => [
        'installed' => true,
    ],
    'controllerMap' => [
        'fixture' => [
            'class'           => 'yii\faker\FixtureController',
            'fixtureDataPath' => '@tests/codeception/fixtures',
            'namespace'       => 'tests\codeception\fixtures',
            'templatePath'    => '@tests/codeception/templates',
        ],
    ],
    'components' => [
        'db' => [
            'charset'  => 'utf8',
            'dsn'      => 'mysql:host=localhost;dbname=tradesf_test',
            'password' => '',
            'username' => 'root',
        ],
        'mailer' => [
            'useFileTransport' => true,
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName'  => true,
        ],
    ],
];
```


You will notice we specify the DB u/p and scheme as well as run the tests on a localhost:8080 services. Thus far this has worked out great using the phpBrowser, some time next week I will be circling back and trying to get phantomJs browser working correctly.

Hope this helps. Feel free to message me if you have any questions.
